-- MySQL Script generated by MySQL Workbench
-- Sat Feb 10 11:39:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria_Pirlo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria_Pirlo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria_Pirlo` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria_Pirlo` ;

-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Provincia_id` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`),
  UNIQUE INDEX `idLocalidad_UNIQUE` (`idLocalidad` ASC) VISIBLE,
  INDEX `idProvincia_idx` (`Provincia_id` ASC) VISIBLE,
  CONSTRAINT `idProvincia`
    FOREIGN KEY (`Provincia_id`)
    REFERENCES `Pizzeria_Pirlo`.`Provincia` (`idProvincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Clientes` (
  `Clientes_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Código_Postal` INT NOT NULL,
  `Localidad_id` INT NOT NULL,
  `Provincia_id` INT NOT NULL,
  `Teléfono` INT NOT NULL,
  PRIMARY KEY (`Clientes_id`),
  UNIQUE INDEX `Clientes_id_UNIQUE` (`Clientes_id` ASC) VISIBLE,
  INDEX `idLocalidad_idx` (`Localidad_id` ASC) VISIBLE,
  CONSTRAINT `idLocalidad`
    FOREIGN KEY (`Localidad_id`)
    REFERENCES `Pizzeria_Pirlo`.`Localidad` (`idLocalidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Tienda` (
  `Tienda_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Localidad_id` INT NOT NULL,
  `Provincia_id` INT NOT NULL,
  UNIQUE INDEX `Tienda_id_UNIQUE` (`Tienda_id` ASC) VISIBLE,
  PRIMARY KEY (`Tienda_id`),
  INDEX `idLocalidad_idx` (`Localidad_id` ASC) VISIBLE,
  CONSTRAINT `idLocalidad`
    FOREIGN KEY (`Localidad_id`)
    REFERENCES `Pizzeria_Pirlo`.`Localidad` (`idLocalidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Categoría_Pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Categoría Pizzas` (
  `Categoria_Pizzas_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Categoria_Pizzas_id`),
  UNIQUE INDEX `Categoria_Pizzas_id_UNIQUE` (`Categoria_Pizzas_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Categorías_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Categorías_Productos` (
  `Categorías_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Categorías_id`),
  UNIQUE INDEX `Categorías_id_UNIQUE` (`Categorías_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Productos` (
  `Productos_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `idCategoría` INT NOT NULL,
  `idPizzas` INT NOT NULL,
  `Categorías_Productos_Categorías_id` INT NOT NULL,
  `Categorías_Productos_Categorías_id1` INT NOT NULL,
  `Pedido_Pedido_id` INT NOT NULL,
  `Pedido_Pedido_id1` INT NOT NULL,
  `Pedido_Pedido_id2` INT NOT NULL,
  `Pedido_Pedido_id3` INT NOT NULL,
  PRIMARY KEY (`Productos_id`, `Categorías_Productos_Categorías_id`, `Categorías_Productos_Categorías_id1`, `Pedido_Pedido_id`, `Pedido_Pedido_id1`, `Pedido_Pedido_id2`, `Pedido_Pedido_id3`),
  UNIQUE INDEX `Productos_id_UNIQUE` (`Productos_id` ASC) VISIBLE,
  UNIQUE INDEX `idPizzas_UNIQUE` (`idPizzas` ASC) VISIBLE,
  UNIQUE INDEX `idCategoría_UNIQUE` (`idCategoría` ASC) VISIBLE,
  CONSTRAINT `Categorías_Pizzas_id`
    FOREIGN KEY (`idPizzas`)
    REFERENCES `Pizzeria_Pirlo`.`Categoría Pizzas` (`Categoria_Pizzas_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Categoría_Productos_id`
    FOREIGN KEY (`idCategoría`)
    REFERENCES `Pizzeria_Pirlo`.`Categorías_Productos` (`Categorías_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Pedido` (
  `Pedido_id` INT NOT NULL,
  `idTienda` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Tipo_Pedido` VARCHAR(45) NOT NULL,
  `Cantidad_Productos` TINYINT(3) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `idProductos` INT NOT NULL,
  UNIQUE INDEX `Cliente_id_UNIQUE` (`Pedido_id` ASC) VISIBLE,
  PRIMARY KEY (`Pedido_id`),
  INDEX `Cliente:id_idx` (`idCliente` ASC) VISIBLE,
  INDEX `Tienda_id_idx` (`idTienda` ASC) VISIBLE,
  INDEX `Productos_id_idx` (`idProductos` ASC) VISIBLE,
  CONSTRAINT `Cliente_id`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Pizzeria_Pirlo`.`Clientes` (`Clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Tienda_id`
    FOREIGN KEY (`idTienda`)
    REFERENCES `Pizzeria_Pirlo`.`Tienda` (`Tienda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Productos_id`
    FOREIGN KEY (`idProductos`)
    REFERENCES `Pizzeria_Pirlo`.`Productos` (`Productos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Trabajador` (
  `Trabajador_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `NIF` INT NOT NULL,
  `Teléfono` INT NOT NULL,
  `idTienda` INT NOT NULL,
  `Puesto_en_Tienda` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Trabajador_id_UNIQUE` (`Trabajador_id` ASC) VISIBLE,
  PRIMARY KEY (`Trabajador_id`),
  INDEX `Tienda_id_idx` (`idTienda` ASC) VISIBLE,
  CONSTRAINT `Tienda_id`
    FOREIGN KEY (`idTienda`)
    REFERENCES `Pizzeria_Pirlo`.`Tienda` (`Tienda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria_Pirlo`.`Reparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria_Pirlo`.`Reparto` (
  `idReparto` INT NOT NULL AUTO_INCREMENT,
  `Trabajodor_id` INT NOT NULL,
  `Fecha_Hora` DATETIME NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idReparto`),
  UNIQUE INDEX `idReparto_UNIQUE` (`idReparto` ASC) VISIBLE,
  INDEX `Trabajador_id_idx` (`Trabajodor_id` ASC) VISIBLE,
  INDEX `Pedido_id_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `Trabajador_id`
    FOREIGN KEY (`Trabajodor_id`)
    REFERENCES `Pizzeria_Pirlo`.`Trabajador` (`Trabajador_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Pedido_id`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Pizzeria_Pirlo`.`Pedido` (`Pedido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
