-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 10:06:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul_d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul_d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul_d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul_d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Proveedor` (
  `Proveedor_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Dirección` VARCHAR(25) NOT NULL,
  `Ciudad` VARCHAR(20) NOT NULL,
  `Código_Postal` SMALLINT(5) UNSIGNED NOT NULL,
  `País` VARCHAR(20) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Fax` INT NOT NULL,
  `NIF` INT NOT NULL,
  PRIMARY KEY (`Proveedor_id`),
  UNIQUE INDEX `Proveedor_id_UNIQUE` (`Proveedor_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Gafas` (
  `Gafas_id` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(30) NOT NULL,
  `Graduación_OI` DECIMAL(4,2) NOT NULL,
  `Graduación_OD` DECIMAL(4,2) NOT NULL,
  `Montura` VARCHAR(20) NOT NULL,
  `Color_Montura` VARCHAR(20) NOT NULL,
  `Color_Cristal` VARCHAR(20) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `idProovedor` INT NOT NULL,
  PRIMARY KEY (`Gafas_id`),
  UNIQUE INDEX `Gafas_id_UNIQUE` (`Gafas_id` ASC) VISIBLE,
  UNIQUE INDEX `Proveedor_id_UNIQUE` (`idProovedor` ASC) VISIBLE,
  CONSTRAINT `Proveedor_id`
    FOREIGN KEY (`idProovedor`)
    REFERENCES `Cul_d'Ampolla`.`Proveedor` (`Proveedor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Clientes` (
  `Clientes_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Dirección` VARCHAR(25) NOT NULL,
  `Ciudad` VARCHAR(20) NOT NULL,
  `Código_Postal` SMALLINT(5) NOT NULL,
  `País` VARCHAR(20) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Email` VARCHAR(30) NULL,
  `Fecha_Registro` DATE NOT NULL,
  `Recomendado` INT NOT NULL,
  PRIMARY KEY (`Clientes_id`),
  UNIQUE INDEX `Clientes_id_UNIQUE` (`Clientes_id` ASC) VISIBLE,
  UNIQUE INDEX `Recomendado_UNIQUE` (`Recomendado` ASC) VISIBLE,
  CONSTRAINT `Cliente_id`
    FOREIGN KEY (`Recomendado`)
    REFERENCES `Cul_d'Ampolla`.`Clientes` (`Clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Empleado` (
  `Empleado_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `NIF` INT NOT NULL,
  UNIQUE INDEX `Empleado_id_UNIQUE` (`Empleado_id` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  PRIMARY KEY (`Empleado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Venta` (
  `Venta_id` INT NOT NULL AUTO_INCREMENT,
  `idClientes` INT NOT NULL,
  `idGafas` INT NOT NULL,
  `idEmpleados` INT NOT NULL,
  `Fecha_Venta` DATE NOT NULL,
  PRIMARY KEY (`Venta_id`),
  UNIQUE INDEX `Venta_id_UNIQUE` (`Venta_id` ASC) VISIBLE,
  UNIQUE INDEX `Clientes_id_UNIQUE` (`idClientes` ASC) VISIBLE,
  UNIQUE INDEX `Gafas_id_UNIQUE` (`idGafas` ASC) VISIBLE,
  UNIQUE INDEX `Empleado_id_UNIQUE` (`idEmpleados` ASC) VISIBLE,
  CONSTRAINT `Clientes_id`
    FOREIGN KEY (`idClientes`)
    REFERENCES `Cul_d'Ampolla`.`Clientes` (`Clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Gafas_id`
    FOREIGN KEY (`idGafas`)
    REFERENCES `Cul_d'Ampolla`.`Gafas` (`Gafas_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Empleado_id`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `Cul_d'Ampolla`.`Empleado` (`Empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
